"""phase 3: voice_profiles, narration_jobs

Revision ID: 247d0c336848
Revises: fa00d9d5942a
Create Date: 2026-05-03 07:41:35.212403

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '247d0c336848'
down_revision: str | None = 'fa00d9d5942a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sample_storage_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('sample_public_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('provider_voice_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('reference_text', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'FAILED', name='voicestatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_status'), 'voice_profiles', ['status'], unique=False)
    op.create_table('narration_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('voice_id', sa.Uuid(), nullable=True),
    sa.Column('script', sqlmodel.sql.sqltypes.AutoString(length=20000), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SYNTHESIZING', 'UPLOADING', 'SUCCEEDED', 'FAILED', name='narrationstatus'), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('public_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('captions_json', sqlmodel.sql.sqltypes.AutoString(length=200000), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['voice_id'], ['voice_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narration_jobs_project_id'), 'narration_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_narration_jobs_status'), 'narration_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_narration_jobs_voice_id'), 'narration_jobs', ['voice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_narration_jobs_voice_id'), table_name='narration_jobs')
    op.drop_index(op.f('ix_narration_jobs_status'), table_name='narration_jobs')
    op.drop_index(op.f('ix_narration_jobs_project_id'), table_name='narration_jobs')
    op.drop_table('narration_jobs')
    op.drop_index(op.f('ix_voice_profiles_status'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    # ### end Alembic commands ###
