"""phase 4: social_accounts, publish_jobs

Revision ID: 4b58dfda1f15
Revises: 247d0c336848
Create Date: 2026-05-03 07:50:31.029825

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4b58dfda1f15'
down_revision: str | None = '247d0c336848'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('YOUTUBE', 'TIKTOK', 'INSTAGRAM', name='socialplatform'), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('extra_json', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_accounts_external_id'), 'social_accounts', ['external_id'], unique=False)
    op.create_index(op.f('ix_social_accounts_platform'), 'social_accounts', ['platform'], unique=False)
    op.create_table('publish_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('export_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('YOUTUBE', 'TIKTOK', 'INSTAGRAM', name='socialplatform'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'UNLISTED', 'PUBLIC', name='publishvisibility'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADING', 'PROCESSING', 'SUCCEEDED', 'FAILED', name='publishstatus'), nullable=False),
    sa.Column('platform_media_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('platform_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], ),
    sa.ForeignKeyConstraint(['export_id'], ['export_jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_jobs_account_id'), 'publish_jobs', ['account_id'], unique=False)
    op.create_index(op.f('ix_publish_jobs_export_id'), 'publish_jobs', ['export_id'], unique=False)
    op.create_index(op.f('ix_publish_jobs_platform'), 'publish_jobs', ['platform'], unique=False)
    op.create_index(op.f('ix_publish_jobs_project_id'), 'publish_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_publish_jobs_status'), 'publish_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publish_jobs_status'), table_name='publish_jobs')
    op.drop_index(op.f('ix_publish_jobs_project_id'), table_name='publish_jobs')
    op.drop_index(op.f('ix_publish_jobs_platform'), table_name='publish_jobs')
    op.drop_index(op.f('ix_publish_jobs_export_id'), table_name='publish_jobs')
    op.drop_index(op.f('ix_publish_jobs_account_id'), table_name='publish_jobs')
    op.drop_table('publish_jobs')
    op.drop_index(op.f('ix_social_accounts_platform'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_external_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
