"""phase 2: shots, timeline_items, export_jobs

Revision ID: fa00d9d5942a
Revises: b8c370edc661
Create Date: 2026-05-03 07:32:35.799948

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa00d9d5942a'
down_revision: str | None = 'b8c370edc661'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RENDERING', 'UPLOADING', 'SUCCEEDED', 'FAILED', name='exportstatus'), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('public_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_project_id'), 'export_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_export_jobs_status'), 'export_jobs', ['status'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('aspect_ratio', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('generation_job_id', sa.Uuid(), nullable=True),
    sa.Column('selected_clip_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['selected_clip_id'], ['clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shots_order_index'), 'shots', ['order_index'], unique=False)
    op.create_index(op.f('ix_shots_project_id'), 'shots', ['project_id'], unique=False)
    op.create_table('timeline_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('CLIP', 'AUDIO', 'TEXT', name='timelineitemtype'), nullable=False),
    sa.Column('clip_id', sa.Uuid(), nullable=True),
    sa.Column('source_start_ms', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('transition_in', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('transition_out', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('text_overlay', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('audio_storage_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_items_order_index'), 'timeline_items', ['order_index'], unique=False)
    op.create_index(op.f('ix_timeline_items_project_id'), 'timeline_items', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_items_project_id'), table_name='timeline_items')
    op.drop_index(op.f('ix_timeline_items_order_index'), table_name='timeline_items')
    op.drop_table('timeline_items')
    op.drop_index(op.f('ix_shots_project_id'), table_name='shots')
    op.drop_index(op.f('ix_shots_order_index'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_export_jobs_status'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_project_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    # ### end Alembic commands ###
